package ERP;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;


public class Attendance {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.chrome.driver", "C:\\Webdriver\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();	
		 driver.manage().deleteAllCookies();
			driver.manage().window().maximize();
			driver.get("http://additerpforschool.azurewebsites.net/login");
			driver.findElement(By.xpath("//input[@type='email']")).sendKeys("vilas@additlabs.com");
			driver.findElement(By.xpath("//input[@formcontrolname='password']")).sendKeys("Vilas147@");
			driver.findElement(By.xpath("//button[@type='submit']")).click();
			Thread.sleep(15000);
			driver.findElement(By.xpath("//span[@class='btn btn-primary ng-star-inserted']")).click();
			Thread.sleep(2000);
			driver.findElement(By.xpath("//input[@formcontrolname='schoolname']")).sendKeys("abc");
			driver.findElement(By.xpath("//input[@formcontrolname='alias']")).sendKeys("abc");
			driver.findElement(By.xpath("//input[@formcontrolname='country']")).sendKeys("abc");
			driver.findElement(By.xpath("//input[@formcontrolname='state']")).sendKeys("abc");
			driver.findElement(By.xpath("//input[@formcontrolname='city']")).sendKeys("abc");
			driver.findElement(By.xpath("//input[@formcontrolname='pincode']")).sendKeys("1234");
			driver.findElement(By.xpath("//button[@type='submit']")).click();
			Thread.sleep(10000);
		    driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-subscribed-page/div/div[2]/div/div/div")).click();
			 Thread.sleep(3000);
			 driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-home/div[2]/div/div[1]")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-sub-modules/div[2]/div/div[4]")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-view-options/div[2]/div/div[1]/div")).click();
				Thread.sleep(4000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-timetable-template/div/div/div/form/div[1]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"schoolStartTime\"]")).sendKeys("0900AM");
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"schoolEndTime\"]")).sendKeys("0400PM");
				Thread.sleep(1000);
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"nameOfTemplate\"]")).sendKeys("Sri Time Table");
                Thread.sleep(2000);
				JavascriptExecutor jse4 = (JavascriptExecutor)driver;
				jse4.executeScript("window.scrollBy(0,600)");
				Thread.sleep(2000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-timetable-template/div/div/div/form/div[2]/div/div[3]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-timetable-template/div/div/div/form/div[2]/div/div[1]/div[3]/div/div/button")).click();
				Select SourceTemplate = new Select(driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[1]/div[1]/div/div/div[1]/div/div/div/select")));
				SourceTemplate.selectByVisibleText("Sri Time Table");
				Select CourceSelect = new Select(driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[1]/div[1]/div/div/div[2]/div/div/div/select")));
				CourceSelect.selectByVisibleText("CBSE - Class 1 - A - 2023 ");
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(4000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-timetable-template/ol/li[4]/a")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-view-options/div[2]/div/div[2]/div")).click();
				Thread.sleep(2000);
				Select SelectGrade = new Select(driver.findElement(By.xpath("//*[@id=\"CalendarTemplates\"]")));
				SelectGrade.selectByVisibleText("CBSE - Class 1 - A - 2023 ");
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"0_0_0\"]")).click();
				Thread.sleep(2000);
				Select Class1 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Class1.selectByVisibleText("Physics");
				Thread.sleep(1000);
				Select Teacher1 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Teacher1.selectByVisibleText("Sri001_Anitha Kumari ");
				Thread.sleep(1000);
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"0_0_1\"]")).click();
				Select Class2 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Class2.selectByVisibleText("Paper Craft");
				Thread.sleep(1000);
				Select Teacher2 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Teacher2.selectByVisibleText("Sri001_Anitha Kumari ");
				Thread.sleep(1000);
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"0_0_3\"]")).click();
				Select Class3 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Class3.selectByVisibleText("Physics");
				Thread.sleep(1000);
				Select Teacher3 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Teacher3.selectByVisibleText("Sri001_Anitha Kumari ");
				Thread.sleep(1000);
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"0_0_4\"]")).click();
				Select Class4 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Class4.selectByVisibleText("Paper Craft");
				Thread.sleep(1000);
				Select Teacher4 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Teacher4.selectByVisibleText("Sri001_Anitha Kumari ");
				Thread.sleep(1000);
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"0_0_6\"]")).click();
				Select Class5 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Class1.selectByVisibleText("Physics");
				Thread.sleep(1000);
				Select Teacher5 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Teacher5.selectByVisibleText("Sri001_Anitha Kumari ");
				Thread.sleep(1000);
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("//*[@id=\"0_0_7\"]")).click();
				Select Class6 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Class6.selectByVisibleText("Paper Craft");
				Thread.sleep(1000);
				Select Teacher6 = new Select(driver.findElement(By.xpath("//*[@id=\"subject\"]")));
				Teacher6.selectByVisibleText("Sri001_Anitha Kumari ");
				Thread.sleep(1000);
				driver.findElement(By.xpath("/html/body/ngb-modal-window/div/div/div[2]/form/div[2]/button")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-class-timetable/ol/li[4]/a")).click();
				Thread.sleep(2000);
				driver.findElement(By.xpath("/html/body/app-dashboard/div/main/app-view-options/div[2]/div/div[3]/div")).click();

	}

}
